language: cpp

install:
  - sudo pip install codecov
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libgtest-dev
  - mkdir build_gtest
  - cd build_gtest
  - cmake /usr/src/gtest
  - sudo make
  - sudo cp libgtest* /usr/lib
  - cd ..


script:
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - ./Test

addons:
  apt:
    packages: lcov

after_success:
  # Create lcov report
  - lcov --capture --directory ./build/CMakeFiles/Test.dir/ --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info # debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
